openapi: 3.0.3
info:
  title: Apideck
  version: 0.0.1
servers:
  - url: "https://unify.apideck.com"
externalDocs:
  description: Apideck Developer Docs
  url: "https://developers.apideck.com"
security:
  - apiKey: []
paths:
  /hello:
    get:
      operationId: hello
      responses:
        "200":
          description: "Say hello"
          content: {}
  /space/rockets/{rocketId}:
    get:
      operationId: rocketsOne
      responses:
        "200":
          description: "Get a rocket"
          content: {}
  /space/rockets:
    get:
      operationId: rockets
      responses:
        "200":
          description: "Get a list of rockets"
          content: {}
